from charm.toolbox.pairinggroup import *
from charm.core.engine.util import bytesToObject
import cryptocode
import block_int
import ipfshttpclient
import json
import os
import base64
from maabe_class import *
from decouple import config
import sqlite3
import argparse
from authorities_info import authorities_addresses_and_names_separated

# Merge multiple dictionaries into one, with latter dicts taking precedence
def merge_dicts(*dict_args):
    """
    Given any number of dicts, shallow copy and merge into a new dict,
    precedence goes to key value pairs in latter dicts.
    """
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result

# Retrieve data from the blockchain using the Authority address and process instance ID
def retrieve_data(authority_address, process_instance_id):
    authorities = block_int.retrieve_authority_names(authority_address, process_instance_id)
    public_parameters = block_int.retrieve_parameters_link(authority_address, process_instance_id)
    return authorities, public_parameters

# Generate public parameters
def generate_public_parameters(process_instance_id):
    check_authorities = []
    check_parameters = []
    for authority_address in authorities_addresses:
        data = retrieve_data(authority_address, process_instance_id)
        check_authorities.append(data[0])
        check_parameters.append(data[1])
    if len(set(check_authorities)) == 1 and len(set(check_parameters)) == 1:
        getfile = api.cat(check_parameters[0])
        x.execute("INSERT OR IGNORE INTO public_parameters VALUES (?,?,?)",
                  (str(process_instance_id), check_parameters[0], getfile))
        conn.commit()

# Decode Base64 data and write to a file
def base64_to_file(encoded_data, output_file_path):
    try:
        decoded_data = base64.b64decode(encoded_data.encode('utf-8'))
        with open(output_file_path, 'wb') as file:
            file.write(decoded_data)
    except Exception as e:
        print(f"Error decoding Base64 to file: {e}")

# Retrieve public parameters from the database or generate them if not available
def retrieve_public_parameters(process_instance_id):
    x.execute("SELECT * FROM public_parameters WHERE process_instance=?", (str(process_instance_id),))
    result = x.fetchall()
    try:
        public_parameters = result[0][2]
    except IndexError:
        generate_public_parameters(process_instance_id)
        x.execute("SELECT * FROM public_parameters WHERE process_instance=?", (str(process_instance_id),))
        result = x.fetchall()
        public_parameters = result[0][2]
    return public_parameters

# Perform actual decryption using the provided parameters and save the decrypted file
def actual_decryption(remaining, public_parameters, user_sk, output_folder):
    test = remaining['CipheredKey'].encode('utf-8')
    ct = bytesToObject(test, groupObj)
    v2 = maabe.decrypt(public_parameters, user_sk, ct)
    v2 = groupObj.serialize(v2)
    output_folder_path = os.path.abspath(output_folder)
    decryptedFile = cryptocode.decrypt(remaining['EncryptedFile'], str(v2))
    base64_to_file(decryptedFile, output_folder_path+"/"+remaining['FileName'])

# Main function to start the decryption process
def start(process_instance_id, message_id, slice_id, sender_address, output_folder, merged):
    response = retrieve_public_parameters(process_instance_id)
    public_parameters = bytesToObject(response, groupObj)
    # Define hash functions H and F
    H = lambda x: self.group.hash(x, G2)
    F = lambda x: self.group.hash(x, G2)
    public_parameters["H"] = H
    public_parameters["F"] = F
    for authority_address in authorities_addresses:
        # Retrieve user secret keys generated by Authorities
        x.execute("SELECT * FROM authorities_generated_decription_keys WHERE process_instance=? AND authority_address=? AND reader_address=?",
                  (str(process_instance_id), authority_address, sender_address))
        result = x.fetchall()
        user_sk1 = result[0][3]
        user_sk1 = bytesToObject(user_sk1, groupObj)
        merged = merge_dicts(merged, user_sk1)
    user_sk = {'GID': sender_address, 'keys': merged}
    # Retrieve ciphertext link from IPFS
    response = block_int.retrieve_MessageIPFSLink(message_id)
    ciphertext_link = response[0]
    getfile = api.cat(ciphertext_link)
    ciphertext_dict = json.loads(getfile)
    correctly_decrypted = False
    if ciphertext_dict['metadata']['process_instance_id'] == int(process_instance_id) \
            and ciphertext_dict['metadata']['message_id'] == int(message_id):
        slice_check = ciphertext_dict['header']
        # Decrypt the relevant slice
        if len(slice_check) == 1:
            actual_decryption(ciphertext_dict['header'][0], public_parameters, user_sk, output_folder)
            correctly_decrypted = True
        elif len(slice_check) > 1:
            for remaining in slice_check:
                if remaining['Slice_id'] == slice_id:
                    actual_decryption(remaining, public_parameters, user_sk, output_folder)
                    correctly_decrypted = True
    if correctly_decrypted == False:
        raise RuntimeError("Decryption error: Please check that the message_id and slice_id are specified correctly. Note that caching is only applicable for the most recent encrypted message.")

if __name__ == '__main__':
    groupObj = PairingGroup('SS512')
    maabe = MaabeRW15(groupObj)
    api = ipfshttpclient.connect('/ip4/127.0.0.1/tcp/5001')
    process_instance_id_env = config('PROCESS_INSTANCE_ID')
    process_instance_id = int(process_instance_id_env)
    parser = argparse.ArgumentParser(description="Reader details",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-m", "--message_id", type=int, help="message id")
    parser.add_argument("-s", "--slice_id", type=int, help="slice id")
    parser.add_argument("--reader_name", type=str, help="Name of the requester")
    parser.add_argument("-o", "--output_folder", type=str, help="Path to the output folder")
    args = parser.parse_args()
    # Connection to SQLite3 data_owner database
    conn = sqlite3.connect('../databases/reader/reader.db')
    x = conn.cursor()
    authorities_addresses, authorities_names = authorities_addresses_and_names_separated()
    message_id = args.message_id
    slice_id = args.slice_id
    sender_address = config(args.reader_name + '_ADDRESS')
    output_folder = args.output_folder
    merged={}
    # Start the decryption process
    start(process_instance_id, message_id, slice_id, sender_address, output_folder, merged)

